### ISSUE TITLE
it will be excellent if FlexboxLayout support overlay 

### ISSUE THREAD

**Issue by Shuijwan** [google/flexbox-layout#130]
currently all the child in FlexboxLayout will push each other in the parent, there is no way to make the child view overlay show on other views.

**Comment by thagikura** [comment]
Hi,

Thanks for your suggestion. Do you want to put a view on top of everything in a FlexboxLayout like [this thread](http://stackoverflow.com/questions/7519160/android-overlay-a-view-ontop-of-everything)?
If so, I recommend to wrap the FlexboxLayout by a FrameLayout or RelativeLayout as in that thread.
Because the addition of the overlay feature pretty diverse from the original Flexbox spec and I think not that many developers use that. Plus it can be done in another simpler way (it introduces another nested layout though)

**Comment by thagikura** [comment]
Closing this for now. Please reopen it if my understanding is not correct. Thanks!

**Comment by Shuijwan** [comment]
Thanks for your answer, I know it can implement the overlay effect with FrameLayout or RelativeLayout,  just feel that if FlexboxLayout support the overlay feature, then we can almost do any layout just in FlexboxLayout :-).
