### ISSUE TITLE
no need to measure child when it is GONE

### ISSUE THREAD

**Issue by Shuijwan** [google/flexbox-layout#170]
Hi, seems there is no need to measure GONE child in stretchViews().

**Comment by thagikura** [comment]
Thanks for bringing this up!
You are right, it's not needed to measure a view if the view's visibility is GONE in stretchViews.

The fix is already applied to the [dev_recyclerview](https://github.com/google/flexbox-layout/tree/dev_recyclerview) branch, which is going to be merged to master once it gets stable.
So I'll keep this issue open, once it's merged to master, I'll close this.

**Comment by Shuijwan** [comment]
Thanks 👍

**Comment by isswu** [comment]
Good

**Comment by thagikura** [comment]
Fixed by now.
