### ISSUE TITLE
constraintlayout vs flexbox-layout 

### ISSUE THREAD

**Issue by sandys** [google/flexbox-layout#173]
hi guys,
how does flexbox layout fit with constraintlayout ? we are looking to build interfaces inspired by the flexbox way of working.

we are unsure of how both these libraries fit with each other. Both are "google recommended". Constraintlayout is even part of "best practices" - https://developer.android.com/training/constraint-layout/index.html

what is even more puzzling is that flexbox-layout does not build on top of constraintlayout. if there was some info on how an end-user should think about using both of these.... that would be awesome.

**Comment by thagikura** [comment]
The simple answer is you can use the appropriate one depending on your use case.

I think ConstraintLayout can cover most of the use cases and boosts your productivity with the new layout editor, also there should be performance advantage by reducing the view hierarchy.
But there are still some use cases where FlexboxLayout can be used more effectively. For example:

- The case where you want to put views sequentially and put a view in a new line if not enough space is left while the width may be changed (due to a device factor, orientation changes or the window resizing in the multi window mode) like this [one](https://github.com/google/flexbox-layout/wiki/Target-use-cases#fluid-grid) or this [one](https://github.com/google/flexbox-layout/pull/59)

- Scrollable view. As in this [issue](https://github.com/google/flexbox-layout/issues/2), the integration of FlexboxLayout with RecyclerView is under development. It offers the same functionality in a scrollable view. That use case is useful for a google photo like app or a news like app (where you want to put various widths of views)

> what is even more puzzling is that flexbox-layout does not build on top of constraintlayout.

Is this happening in your project? 
FlexboxLayout should build on top of ConstraintLayout since both layouts are just classes that extend ViewGroup like other layouts (e.g. LinearLayout, RelativeLayout). So if it doesn't build, it's an issue, please file that, then I can fix it.

**Comment by thagikura** [comment]
By the way this is not an issue with the FlexboxLayout, so GitHub issue is not the right place to discuss is. Let me close this.

**Comment by sandys** [comment]
@thagikura hi - i dont want to reopen this issue, but where else do we discuss enhancements and usecases ? I googled a lot but did not find any other resource/forum/slack-channel/google-group. So I apologize in advance for the comments.

**Comment by thagikura** [comment]
@sandys please file an GitHub issue for the enhancements. For the discussion, I think you can expect opinions from others by creating a thread in other community sites (like Reddit, Hacker News). Or if it's just a question, you can ask me on twitter.

Does that answer your question?
