### ISSUE TITLE
[FlexboxLayoutManager] Dynamic column support

### ISSUE THREAD

**Issue by MGaetan89** [google/flexbox-layout#212]
I am trying to use the `FlexboxLayoutManager` to create a dynamic list where the number of columns can be changed dynamically. To do this, I was thinking about using the `wrapBefore` attribute, but unfortunately, it does not seem to work. Even in the playground application I was not able to do what I want to achieve.

My configuration is the following:
- `FlexboxLayoutManager`
  - `alignItens` = `FLEX_START`
  - `flexDirection` = `COLUMN`
  - `flexWrap` = `WRAP`
  - `justifyContent` = `FLEX_START`
- `RecyclerView` item: nothing except `wrapBefore` = `true` when necessary

I think that the problem comes from my layout, which has its width set to `match_parent`. If I set the width to a specific value (like `200dp`), it works, but I want my column to fill the space horizontally. Is there a way to do this? I am currently using version 0.3.0-alpha2.
Don't hesitate to ask if you need more information.

**Comment by thagikura** [comment]
If the the number of flex lines is 1, you can set alignItems.STRETCH or the number of flex lines is greater than 1, there is no way to fill the horizontal space. 
Because RecyclerView expects a scrolling horizontally if you set flexDirection as COLUMN.
So setting alignContent is not supported (it's the Flexbox specification) as it works only when the horizontal length has a fixed value, instead of the infinite value (if it scrolls horizontally, the horizontal length is considered as infinite internally).

Instead, I thought if you use FlexboxLayout and setting the following attributes would work to fill the horizontal space.
alignItens = STRETCH
alignContent = STRETCH
flexDirection = COLUMN
flexWrap = WRAP
justifyContent = FLEX_START

Please let me know if it works for you.

Also noticed there was an issue in the demo app in the dev_recyclerview branch that wrapBefore change wasn't reflected, which should be fixed by #214.
(Library wasn't for blame that wrapBefore attribute didn't work)

**Comment by MGaetan89** [comment]
Thanks for the explanations. I didn't try to see if it scrolls horizontally. So it is working as expected.
I switch to a classic FlexboxLayout to achieve what I want and it is working as expected.

**Comment by Anki1514** [comment]
![hdhdhdhdf](https://user-images.githubusercontent.com/16363785/40877301-426fd658-669c-11e8-826f-5a0e64c3fd5e.png)
hello can i achieve the above recyclerview with flex layout manager if yes plz help

**Comment by gentlemanZ** [comment]
@thagikura HI really appreciate the demo and effort. I have a similar question. What I am trying to achieve is that in a recyclerView, I hope to only wrap when I want by setting wrapBefore to true. I wonder if that is doable? Thanks!
