### ISSUE TITLE
Feature request: space-evenly

### ISSUE THREAD

**Issue by soumya92** [google/flexbox-layout#284]
With space-around, the space between the first item and the left edge of the flexbox is half the space between items. This is probably because the items have similar spacing to their left and right, but between two items that spacing gets added twice.

It would be nice to have an option for consistent spacing everywhere, even though it's not supported in CSS. Thoughts?

**Comment by thagikura** [comment]
Thanks for the suggestion, that sounds a reasonable request.

I may be wrong, but I thought I saw a similar attribute in CSS for Flexbox or Grid.
Anyway, I'll keep this as an enhancement.

**Comment by soumya92** [comment]
Yeah, turns out CSS Grid already supports space-evenly, and Firefox just started shipping support for space-evenly in flexbox as well

**Comment by jjhesk** [comment]
is there a support for spacing between items?

**Comment by feinstein** [comment]
This would be great to have, some sort of margin that will be equal between all the items and between an item and the screen borders.

**Comment by thagikura** [comment]
This is now implemented. Will be released in the next release.

**Comment by feinstein** [comment]
@thagikura is it possible to make the items centered but with a left justification? For example, if I have 5 items, 3 on the first row and 2 on the second row, they will be centered on the screen, but the 2 items on the second row will be aligned with the 1st and the 2nd items on the first row, as if this was a table? Because right now if I justify them to be centered, the 1st item  of the second row will be in the middle of the 1st and 2nd items from the first row.

If it's confusing, please let me know and I will send you a picture.

**Comment by thagikura** [comment]
Hi @feinstein, 

Could you send me a picture?
Also if it's not part of the specification in the original justify-content attribute, it might be difficult to include it in this library because that is going to be counter intuitive.

**Comment by feinstein** [comment]
@thagikura right now we can have this:

![image](https://user-images.githubusercontent.com/8120472/36314706-c888a18a-131c-11e8-8ef3-2323874c49ae.png)

Or this:

![image](https://user-images.githubusercontent.com/8120472/36314904-64489792-131d-11e8-9da4-1de3412207a2.png)


What I wanted is this:

![image](https://user-images.githubusercontent.com/8120472/36315007-b6a4720e-131d-11e8-8e7c-17158b50c604.png)
