### ISSUE TITLE
last view is arranged next line when specific width

### ISSUE THREAD

**Issue by ttymsd** [google/flexbox-layout#478]
- [x] I have searched [existing issues](https://github.com/google/flexbox-layout/issues) and confirmed this is not a duplicate

## Issues and steps to reproduce
When arrange multiple Views on one line to Flexbox Layout with certain width, last view is arranged to next line.
It is case of FlexboxLayout is 399dp and use flexWrap=wrap, view's layoutParams.flexBasisPercent is 0.25f.

## Expected behavior
I think, in this case flexbox layout arrange four view on one line.
Are there plans to be fixed?

## Version of the flexbox library
1.1.0

## Link to code
https://github.com/google/flexbox-layout/compare/master...ttymsd:add-specific-width

**Comment by thagikura** [comment]
Hi,

Thanks for the report. Unfortunately, I don't think it's a bug since there must be some rounding errors depending on the width of the FlexboxLayout, number of children in a row, and each of flexBasisPercent value.

If you want to guarantee the certain number of views are placed in a row while filling the remaining space, I recommend to set the flexBasisPercent value a bit smaller than the actual parent width (like 0.24 in the case above) and set the flexGrow to positive value like 1 for each child.
