### ISSUE TITLE
Writing wiki pages

### ISSUE THREAD

**Issue by lii2** [google/flexbox-layout#81]
I wrote some wiki pages in my repo in an effort to make the documentation more clear:

https://github.com/lii2/flexbox-wiki

*Added an installation page and attributes page
*Updated the sidebar to match
*Added a table of attributes so people could scan through the attributes easily

A question: Am I installing the flexbox layout correct? It seems to be running correctly on my smartphone, but the Android Studio XML design tab is running into rendering problems:

```
Exception raised during rendering: android.graphics.drawable.VectorDrawable_Delegate.nDraw(JJJLandroid/graphics/Rect;ZZ)I
```

**Comment by thagikura** [comment]
Thanks for updating your local wiki.

As I also commented in the #13, I'd like to keep the introductory information such as installation, usage and supported attributes in the README instead of writing it in separate wiki pages. Because README is viewed way more than the wiki pages and read first by developers.
I'd like to let developers start using this library by only reading the README as their first experience.
When developers want to know in detail, then wiki pages are good start. 

So I want to keep such contents (supported attributes, installation) in the README.
It's really appreciated if you can improve the detailed wiki contents. E.g. I filed a couple of wiki improvement ideas as #84 and #85, thanks.

> A question: Am I installing the flexbox layout correct? It seems to be running correctly on my smartphone, but the Android Studio XML design tab is running into rendering problems:

Not sure what caused that, but please try choosing a different API level from the API dropdown in the design tab.

**Comment by thagikura** [comment]
Closing this issue. In favor of other issues related wiki.
