### ISSUE TITLE
I find,onResume() method perform addView(),but does not show，but replaces by LinearLayout,it is normal.And sometimes,in onCreate() method,it does not show.

### ISSUE THREAD

**Issue by qinyongfang** [google/flexbox-layout#90]
I find,onResume() method perform addView(),but does not show， replaces by LinearLayout,it is normal.And sometimes,in onCreate() method,it also does not show.I want to see if you have any such situation.

**Comment by thagikura** [comment]
Hi, 

Thanks for your report.
If I understand your issue correctly, you are calling FlexboxLayout#addView in the onResume method in your app but the added view isn't showing?

If so, is it possible to paste your relevant code and screenshots?

**Comment by qinyongfang** [comment]
Yes,you think right.Even in onCreate() method to request, it will occasionally appear.
My code:
hotSearch xml:
![image](https://cloud.githubusercontent.com/assets/12984157/16411035/baaad8c2-3d57-11e6-953c-4ce6d8c61f5c.png)
history xml:
![image](https://cloud.githubusercontent.com/assets/12984157/16411051/d3c2d094-3d57-11e6-961f-4cd363d751da.png)
in onCreate() method to request to get hotSearchDatas:
![image](https://cloud.githubusercontent.com/assets/12984157/16411102/0ed8b220-3d58-11e6-884b-91d329fda8a0.png)
in onResume() method to request to get historyDatas():
![image](https://cloud.githubusercontent.com/assets/12984157/16411113/19cfed06-3d58-11e6-83da-e1ad0751f657.png)
![image](https://cloud.githubusercontent.com/assets/12984157/16411285/e53a68f4-3d58-11e6-928d-7377836f4d2a.png)
history does not show:
![image](https://cloud.githubusercontent.com/assets/12984157/16411198/7d8a96ca-3d58-11e6-910a-7dc20d4ee86c.png)
back and have a try,it shows:
![image](https://cloud.githubusercontent.com/assets/12984157/16411212/92b3d1d8-3d58-11e6-9fe1-1e3c4aa65d7d.png)
back and have a try,unfortunately,it does not show:
![image](https://cloud.githubusercontent.com/assets/12984157/16411242/b06212ee-3d58-11e6-81b1-3f086579eb4b.png)
thank you.

**Comment by stewForAni** [comment]
use real phone to have a try   －。－

**Comment by thagikura** [comment]
Thanks for pasting the code.
From what I can tell, it's still not clear if the issue is in the FlexboxLayout or in your app.
  
Can you please confirm the following?
- When FlexboxLayout#addView is called, please make sure the method is actually called (i.e. there is not empty data from your logic (history data)) by placing a breakpoint and putting logs.

**Comment by bibisarminbet** [comment]
I am confirm receiving my payment from to direct online pay for my payoneer prepared dabit Mastercard number now? 

My payoneer account id: Bibisarminbet365@yahoo.com
Card name: Bibi Sarmin Alacha 
Card number: 5300 7211 2229 7051
Exp date: 06/19

**Comment by thagikura** [comment]
Hello @qinyongfang,

Is the issue still persistent? Is there anything I can do to investigate it further?

**Comment by qinyongfang** [comment]
I'm sorry, Sir. I was doing something else lately. Thank you very much for your reply. I tried on a real machine, still have this problem. I'm sorry I don't know how to make a screenshot of you, I believe you have seen the previous log records. I'm sure that every request data is successful. Can you try this way?

**Comment by qinyongfang** [comment]
I am not saying that it is not always successful, but that it has a large percentage of it is not successful.

**Comment by thagikura** [comment]
I'm certain it's highly likely the issue is not on the FlexboxLayout. From looking at the source code of the `addView` method, it can't possibly success of fail randomly.

If that happens sporadically, please try to:
- output logs for both cases (success and failure).
- simply call the addView method without fetching the history data and see how it goes.

Anyway, can you please reopen it if you are sure the issue if on the FlexboxLayout?
Thanks.
