### ISSUE TITLE
[Feature Request]Is it possible to support absolute position for flexbox-layout? 

### ISSUE THREAD

**Issue by Kellen-kl** [google/flexbox-layout#92]
Is it possible to support absolute position for flexbox-layout?

**Comment by thagikura** [comment]
Is it like the following attributes you have in mind?

```
<com.google.android.flexbox.FlexboxLayout>
  <View
    layout_width="wrap_content"
    layout_height="wrap_content"
    layout_absoluteOffsetX="xxxdp"
    layout_absoluteOffsetY="yyydp"/>
</com.google.android.flexbox.FlexboxLayout>
```

**Comment by Kellen-kl** [comment]
@thagikura like this：

```xml
<com.google.android.flexbox.FlexboxLayout>
    <View
        layout_width="wrap_content"
        layout_height="wrap_content"
        layout_left="xxxdp"
        layout_right="yyydp"
        layout_position="absolute">
</com.google.android.flexbox.FlexboxLayout>

```

**Comment by thagikura** [comment]
Thanks for your suggestion, but I think adding that absolute positioning to the FlexboxLayout is not the way to go since it completely different from the existing supported attributes nor the CSS spec.

I recommend using ConstraintLayout or RelativeLayout if you want to achieve the similar functionality of this.

Let me close this for now, thanks.

**Comment by ramseysaab** [comment]
Visit:http://www.gogvo.com/affiliates/banners.phpwww.ramsedsay.MyCTFO.comhttp://conversionmail.com/splashpage.php?splashid=1&rid=4508CashGames@email.gsncashgames.comhttp://fairymailz.com/?rid=632https://play.google.com/music/m/Tlxdqrxemub2evkyfaoznwfwq7a?t=Cursed_Female_-_Porno_For_Pyroswww.ramsedsay.MyCTFO.com
