### ISSUE TITLE
[Proposal] Remove Hungarian Notation

### ISSUE THREAD

**Issue by hotchemi** [google/flexbox-layout#95]
I know, it's not a big deal but what do you think about removing hungarian notation from this repo?
In my opinion there is no positive reason to use that because here is the out side of AOSP.
Thx in advance.

**Comment by thagikura** [comment]
Thanks for your suggestion.

Firstly I don't have a strong opinion on whether or not the code should follow Hungarian notation since there isn't a practical advantage whichever way the code follows.
So in that sense, I don't see a practical value in converting the existing code into non-Hungarian style and vice versa.

Secondly when I started the project, I expected the code reviewers and contributors from Google where the majority of Android projects still follow the Hungarian style even outside of AOSP
(Actually there are some non-Hungarian style Android projects though).
So it was quite natural that this project follows the Hungarian style from the beginning.

Does that answer your question?

**Comment by hotchemi** [comment]
Okay, thx for your answer.
